// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package managment

import (
	"tg_bot_backend/api/managment"
)

type ControllerV1 struct{}

func NewV1() managment.IManagmentV1 {
	return &ControllerV1{}
}
