// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"tg_bot_backend/internal/dao/internal"
)

// internalBotDao is an internal type for wrapping the internal DAO implementation.
type internalBotDao = *internal.BotDao

// botDao is the data access object for the table bot.
// You can define custom methods on it to extend its functionality as needed.
type botDao struct {
	internalBotDao
}

var (
	// Bot is a globally accessible object for table bot operations.
	Bot = botDao{
		internal.NewBotDao(),
	}
)

// Add your custom methods and functionality below.
