// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"tg_bot_backend/internal/dao/internal"
)

// internalCentralControlDao is an internal type for wrapping the internal DAO implementation.
type internalCentralControlDao = *internal.CentralControlDao

// centralControlDao is the data access object for the table central_control.
// You can define custom methods on it to extend its functionality as needed.
type centralControlDao struct {
	internalCentralControlDao
}

var (
	// CentralControl is a globally accessible object for table central_control operations.
	CentralControl = centralControlDao{
		internal.NewCentralControlDao(),
	}
)

// Add your custom methods and functionality below.
