// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"tg_bot_backend/internal/dao/internal"
)

// tgUsersDao is the data access object for the table tg_users.
// You can define custom methods on it to extend its functionality as needed.
type tgUsersDao struct {
	*internal.TgUsersDao
}

var (
	// TgUsers is a globally accessible object for table tg_users operations.
	TgUsers = tgUsersDao{internal.NewTgUsersDao()}
)

// Add your custom methods and functionality below.
